### ISSUE TITLE
Correct Margins in Repos page

### ISSUE THREAD

**Issue by DeltaProxima** [swciitg/Hacktoberfest_website#1]
The Margins of the text "Our selected Repos" and "External Repos" is not proper. Correct them

**Comment by Vishnu-Shakya** [comment]
can you assign this issue to me. I want to work on this

**Comment by Hareesh-Nandigrama** [comment]
@Vishnu-Shakya you have been assigned

**Comment by coldrohak** [comment]
Can you assign this to me?

**Comment by Vishnu-Shakya** [comment]
Okay I'll work on it

**Comment by coldrohak** [comment]
@Hareesh-Nandigrama can you explain the expected behaviour and assign this to me?

**Comment by Vishnu-Shakya** [comment]
> Can you assign this to me?
bro some body done before  me

**Comment by RohanKrMahato** [comment]
Hi @DeltaProxima, @Hareesh-Nandigrama, @TheAdich

I have resolved issue #1 and would appreciate it if you could review the changes and proceed with the merge.

Thanks!
