### ISSUE TITLE
Redirection Issue:

### ISSUE THREAD

**Issue by Ashmit-Verma** [swciitg/Hacktoberfest_website#12]
We have encountered an issue with the redirection flow after a registered user revisits. When the user clicks on the "Get Started" button from the landing page, they are successfully redirected to the leaderboard page as expected. However, before reaching the leaderboard, the user is briefly redirected to the registration page, even though they are already registered.

This unintended redirection creates a confusing experience for users.

Expected Behavior:

Once the user has registered, clicking on "Get Started" should directly take them to the leaderboard page, without any intermediate redirection to the registration page.

**Comment by AraanBranco** [comment]
Can you please assign this task to me?

**Comment by Ashmit-Verma** [comment]
> Can you please assign this task to me?

@AraanBranco assigned to you

**Comment by AraanBranco** [comment]
I have completed the task, please don't forget to assign me the task @Ashmit-Verma

**Comment by Ashmit-Verma** [comment]
> I have completed the task, please don't forget to assign me the task @Ashmit-Verma

You are not receiving cookies on landing page so everytime it navigates to profile page everytime thus defeating the purpose , make changes in backend accordingly to get cookies on landing page 

We are having an open source competition Hacktoberfest , we noticed you are yet to register through our website https://swc.iitg.ac.in/hacktoberfest . Do register and appear on our leaderboards .

**Comment by AraanBranco** [comment]
@Ashmit-Verma I made a new PR now validating it in the backend, see if that solves it
