### ISSUE TITLE
Validation Check for database inputs

### ISSUE THREAD

**Issue by Ashmit-Verma** [swciitg/Hacktoberfest_website#14]
Currently, the backend does not have sufficient validation checks for User model inputs, which can lead to issues like invalid or malformed data being stored in the database.

Add validation checks for the following inputs:

-Ensure all required fields are validated before proceeding with the database operations.
-Also make changes in the "year_of_study" in User model changing "junior" and "senior" to "pre-final yearite" and "final yearite" make corresponding changes in the frontend

**Comment by heet434** [comment]
Hi @Ashmit-Verma can I take up this one?

**Comment by Ashmit-Verma** [comment]
> Hi @Ashmit-Verma can I take up this one?

Assigned to you
