### ISSUE TITLE
Minor Frontend Changes on leaderboard Page

### ISSUE THREAD

**Issue by Ashmit-Verma** [swciitg/Hacktoberfest_website#8]
Make the leaderboard page responsive
![Screenshot 2024-10-12 004907](https://github.com/user-attachments/assets/dcf8740d-2983-4c01-a040-4e3ee445812b)
Too much space after leaderboard in phone view
![Screenshot 2024-10-12 005419](https://github.com/user-attachments/assets/67de5fa5-581c-471f-b157-b54fdaf5ce4a)
Also make changes in footer , increase spacing and reduce left and right margin

**Comment by subhamagarrwal** [comment]
kindly assign me this

**Comment by Ashmit-Verma** [comment]
@subhamagarrwal assigned to you

**Comment by Ashmit-Verma** [comment]
Updates? @subhamagarrwal

**Comment by subhamagarrwal** [comment]
hey I've fallen sick; haven't started work; gimme some days

**Comment by Ashmit-Verma** [comment]
Hoping your speedy recovery , take 2-3 more days to fix the issue

**Comment by Ashmit-Verma** [comment]
Hoping you are fine now , I would like to ask about the updates? @subhamagarrwal

**Comment by subhamagarrwal** [comment]
would be starting work tomorrow morning; will make a pr tomorrow

**Comment by Ashmit-Verma** [comment]
> would be starting work tomorrow morning; will make a pr tomorrow

Updates?

**Comment by subhamagarrwal** [comment]
doing it right now

**Comment by lostinvsc** [comment]
I have already solved it, can I make pull request

**Comment by Ashmit-Verma** [comment]
> I have already solved it, can I make pull request

assigned to you......make  the pr

**Comment by lostinvsc** [comment]
done
