### ISSUE TITLE
Add AdminJS Portal for Admin Dashboard

### ISSUE THREAD

**Issue by Ashmit-Verma** [swciitg/Hacktoberfest_website#9]
This issue involves integrating AdminJS into the backend and setting up basic configurations to manage our models through the portal.

**Comment by heet434** [comment]
> This issue involves integrating AdminJS into the backend and setting up basic configurations to manage our models through the portal.

Hi @Ashmit-Verma , can I take up this issue?

**Comment by Ashmit-Verma** [comment]
@heet434 assigned to you
